apiVersion: v2
name: velero
description: A Helm chart for velero

maintainers:
- email: isaacmecchi@gmail.com
  name: isaacmecchi

type: application

appVersion: 1.7.0
version: 2.26.2

dependencies:
- name: velero
  version: 2.26.2
  repository: "https://github.com/mecsys/velero-debug"
